# Generated by Django 3.1.5 on 2021-07-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='model_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
