# Generated by Django 3.1.5 on 2021-07-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_backend', '0002_auto_20210718_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='model_pic',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
