# Generated by Django 3.1.5 on 2021-07-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_backend', '0006_auto_20210718_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
