# Generated by Django 3.1.5 on 2021-07-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_backend', '0008_auto_20210720_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='pic_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
