# Generated by Django 3.1.5 on 2021-07-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_backend', '0009_auto_20210720_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myimage',
            name='pic_id',
        ),
        migrations.AddField(
            model_name='myimage',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
